### ISSUE TITLE
mn create-cli-app --lang=kotlin fails with java version 15

### ISSUE THREAD

**Issue by deining** [micronaut-projects/micronaut-picocli#103]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new cli project (Kotlin):

`mn create-cli-app bug-report --lang=kotlin`

2. Run the project

`gradlew run`

### Expected Behaviour

Project should run successfully

### Actual Behaviour
```
> Task :kaptKotlin
Note: ReflectConfigGen writing to: CLASS_OUTPUT/META-INF/native-image/picocli-generated/reflect-config.jsonNote: ResourceConfigGen writing to: CLASS_OUTPUT/META-INF/native-image/picocli-generated/resource-config.jsonNote: ProxyConfigGen writing to: CLASS_OUTPUT/META-INF/native-image/picocli-generated/proxy-config.jsonwarning: The following options were not recognized by any processor: '[micronaut.processing.incremental, micronaut.processing.module, kapt.kotlin.generated, micronaut.processing.annotations]'
> Task :run FAILED
java.lang.UnsupportedClassVersionError: kot/bug/report/KotBugReportCommand has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"
FAILURE: Build failed with an exception.
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.1.2
- **JDK Version:** java 15 2020-09-15, Java(TM) SE Runtime Environment (build 15+36-1562)

### Additional notes:

The error is caused by the following lines in `build.gradle`:

```
compileKotlin {
    kotlinOptions {
        jvmTarget = '11'
    }
}
```

After removing these lines, project can be compiled successfully.

This is not a big issue, but should be fixed IMHO to make the start for newbies to Micronaut as easy as possible.

**Comment by deining** [comment]
Sorry for the noise. Error on my side, JAVA_HOME pointed to an outdated JDK.
