### ISSUE TITLE
Bean injection fails in native image

### ISSUE THREAD

**Issue by miguelaferreira** [micronaut-projects/micronaut-picocli#166]
I've built a micronaut cli app that runs just fine from a jar. However when I build a native image with graalvm the application fails to start with an error that seems to point to a bean injection problem.

I've made an example that illustrates the problem I'm facing. In the example I create a declarative http client that fetches the html for https://www.google.com, I inject that client in the cli application and use it to print the html to stdout. I've added a test for the client and also extended the cli app test that `mn` generates with the project to check that the html is being printed. 

However, when I build a native image and run that, the application fails to start.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Install GraalVM `sdk install java 21.1.0.r11-grl && sdk use java 21.1.0.r11-grl`
2. Install native-image `~/.sdkman/candidates/java/21.1.0.r11-grl/bin/gu install native-image`
2. Clone `git clone git@github.com:miguelaferreira/example.micronaut.cli.git && cd example.micronaut.cli`
2. Build `./gradlew build nativeImage`
3. Run application `build/native-image/application`

### Expected Behaviour

The application would execute the same way as it executes using `java -jar build/libs/cli-0.1-all.jar`, and print the HTML for https://www.google.com.

### Actual Behaviour

The application fails to start with the following message:
```
17:55:45.541 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [cli]
picocli.CommandLine$InitializationException: Could not instantiate class example.micronaut.CliCommand: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [googleClient] of class: example.micronaut.CliCommand

Message: Error setting field value: No field 'googleClient' found for type: example.micronaut.CliCommand

	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:5516)
	at picocli.CommandLine$Model$CommandUserObject.getInstance(CommandLine.java:11813)
	at picocli.CommandLine$Model$CommandSpec.userObject(CommandLine.java:6251)
	at picocli.CommandLine$Interpreter.clear(CommandLine.java:13006)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13051)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13041)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:12942)
	at picocli.CommandLine.parseArgs(CommandLine.java:1478)
	at picocli.CommandLine.execute(CommandLine.java:2077)
	at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:137)
	at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:114)
	at example.micronaut.CliCommand.main(CliCommand.java:24)
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [googleClient] of class: example.micronaut.CliCommand

Message: Error setting field value: No field 'googleClient' found for type: example.micronaut.CliCommand

	at io.micronaut.context.AbstractBeanDefinition.injectBeanField(AbstractBeanDefinition.java:745)
	at example.micronaut.$CliCommandDefinition.injectBean(Unknown Source)
	at example.micronaut.$CliCommandDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2469)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2384)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2356)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1282)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:752)
	at io.micronaut.context.BeanLocator.findOrInstantiateBean(BeanLocator.java:163)
	at io.micronaut.configuration.picocli.MicronautFactory.create(MicronautFactory.java:73)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:5512)
	... 11 more
Caused by: java.lang.NoSuchFieldError: No field 'googleClient' found for type: example.micronaut.CliCommand
	at io.micronaut.core.reflect.ReflectionUtils.lambda$getRequiredField$2(ReflectionUtils.java:291)
	at java.util.Optional.orElseThrow(Optional.java:408)
	at io.micronaut.core.reflect.ReflectionUtils.getRequiredField(ReflectionUtils.java:291)
	at io.micronaut.context.DefaultFieldInjectionPoint.getField(DefaultFieldInjectionPoint.java:118)
	at io.micronaut.context.DefaultFieldInjectionPoint.set(DefaultFieldInjectionPoint.java:128)
	at io.micronaut.context.AbstractBeanDefinition.injectBeanField(AbstractBeanDefinition.java:739)
	... 22 more
```

### Environment Information

- **Operating System**: macOS Big Sur, version 1.2.3 (20D91)
- **Micronaut Version:** 2.4.2
- **JDK Version:**
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)

### Example Application

https://github.com/miguelaferreira/example.micronaut.cli

**Comment by graemerocher** [comment]
If the fields are private you need to annotate them with `@ReflectiveAccess`
