### ISSUE TITLE
Regression: 1.2.1 cannot instantiate a @Command with constructor injection

### ISSUE THREAD

**Issue by ewirch** [micronaut-projects/micronaut-picocli#7]
How to reproduce: follow the steps in https://micronaut-projects.github.io/micronaut-picocli/latest/guide/#generate to create a sample project (w. Micronaut version 1.2.1). Make sure it runs by executing
```
./gradlew run
```
Add a simple bean:
```
@Singleton
class MySingleton {
}
```
Inject the bean into `MyCommand`:
```
private final MySingleton mySingleton;

@Inject
public void MyCommand(MySingleton mySingleton) {
  this.mySingleton = mySingleton;
}
```
Re-run `./gradlew run`.

Observed: 
```
Exception in thread "main" picocli.CommandLine$InitializationException: Could not instantiate class example.MyCommand: java.lang.NoSuchMethodException: example.MyCommand.<init>()
        at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4747)
        at picocli.CommandLine$Model$CommandReflection.getOrCreateInstance(CommandLine.java:9579)
        at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:9522)
        at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:5116)
        at picocli.CommandLine.<init>(CommandLine.java:223)
        at picocli.CommandLine.run(CommandLine.java:2830)
        at picocli.CommandLine.run(CommandLine.java:2755)
        at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:139)
        at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:117)
        at example.MyCommand.main(MyCommand.java:26)
Caused by: java.lang.NoSuchMethodException: example.MyCommand.<init>()
        at java.base/java.lang.Class.getConstructor0(Class.java:3354)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2558)
        at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4723)
        at io.micronaut.configuration.picocli.MicronautFactory.create(MicronautFactory.java:74)
        at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4746)
        ... 9 more
```

Expected: bean is injected.

Field injection works.
Constructor injection using Micronaut 1.2.0 works as well.

**Comment by graemerocher** [comment]
@remkop any ideas? Is there something else that needed to be changed?

**Comment by remkop** [comment]
@ewirch Could you please provide a full stack trace?

I will try to reproduce but I need some time to set up my environment. A stacktrace may help understanding the problem sooner.

**Comment by ewirch** [comment]
Added stacktrack.

**Comment by remkop** [comment]
@ewirch Awesome, that’s helpful! What version of Java are you using?

**Comment by ewirch** [comment]
And the debug output:
```
16:53:42.232 [main] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: class example.MyCommand
16:53:42.233 [main] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: example.MyCommand] for type: class example.MyCommand
16:53:42.233 [main] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: example.MyCommand]
16:53:42.233 [main] DEBUG i.m.context.DefaultBeanContext - Found concrete candidate [Definition: example.MyCommand] for type: example.MyCommand 
16:53:42.233 [main] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: class example.MySingleton
16:53:42.233 [main] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: example.MySingleton] for type: class example.MySingleton
16:53:42.233 [main] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: example.MySingleton]
16:53:42.233 [main] DEBUG i.m.context.DefaultBeanContext - Found concrete candidate [Definition: example.MySingleton] for type: example.MySingleton 
16:53:42.234 [main] DEBUG io.micronaut.context.lifecycle - Created bean [example.MySingleton@4eeea57d] from definition [Definition: example.MySingleton] with qualifier [null]
16:53:42.234 [main] DEBUG i.m.context.DefaultBeanContext - Registering singleton bean example.MySingleton@4eeea57d for type [example.MySingleton] using bean key example.MySingleton
16:53:42.234 [main] DEBUG io.micronaut.context.lifecycle - Created bean [example.MyCommand@780ec4a5] from definition [Definition: example.MyCommand] with qualifier [null]
16:53:42.234 [main] DEBUG i.m.context.DefaultBeanContext - Stopping BeanContext
16:53:42.234 [main] DEBUG i.m.c.e.ApplicationEventPublisher - Publishing event: io.micronaut.context.event.ShutdownEvent[source=io.micronaut.context.DefaultApplicationContext@4fce136b]
16:53:42.234 [main] DEBUG i.m.context.DefaultBeanContext - Resolving beans for type: <ShutdownEvent> io.micronaut.context.event.ApplicationEventListener 
16:53:42.234 [main] DEBUG i.m.context.DefaultBeanContext - Qualifying bean [io.micronaut.context.event.ApplicationEventListener] from candidates [Definition: io.micronaut.runtime.context.scope.refresh.RefreshScope, Definition: io.micronaut.runtime.http.scope.RequestCustomScope] for qualifier: <ShutdownEvent> 
16:53:42.234 [main] DEBUG i.m.context.DefaultBeanContext - Found no matching beans of type [io.micronaut.context.event.ApplicationEventListener] for qualifier: <ShutdownEvent> 
16:53:42.235 [main] DEBUG io.micronaut.context.lifecycle - Destroying bean [io.micronaut.http.resource.ResourceLoaderFactory@5ef0d29e] with identifier [io.micronaut.http.resource.ResourceLoaderFactory]
```

**Comment by remkop** [comment]
I believe that constructor injection will work if we can make  Micronaut instantiate the `MyCommand` object. Can you annotate the `MyCommand` class with `@Singleton` or `@Prototype` and try again?

I need to investigate more to understand why it used to work in Micronaut 1.2.

**Comment by ewirch** [comment]
Using Java 12 and:
```
targetCompatibility = 11
sourceCompatibility = 11
```
Adding `@Singleton` to `MyCommand` does not change behavior. When I remove `PicocliRunner.run()`, Gradle completes successfully, but `run()` is (obviously) not being invoked then.

**Comment by remkop** [comment]
@ewirch, @graemerocher, I finally figured it out. The culprit is the following line in `MicronautFactory`:

```java
    // io.micronaut.configuration.picocli.MicronautFactory
    public <K> K create(Class<K> cls) throws Exception {
        return ctx.findOrInstantiateBean(cls).orElse(fallbackFactory.create(cls));
    }
```

The problem is that the right-hand side (`fallbackFactory.create(cls)`) is evaluated, regardless of whether the left-hand side returned an empty `Optional` or a non-empty `Optional`.

The Micronaut context successfully constructed a `MyCommand` instance, using constructor injection, but then the `fallbackFactory.create` method is invoked anyway, and this fails...

One solution is to replace the above with:

```java
    public <K> K create(Class<K> cls) throws Exception {
        Optional<K> bean = ctx.findOrInstantiateBean(cls);
        return bean.isPresent() ? bean.get() : fallbackFactory.create(cls);
    }
```

@graemerocher: I will provide a PR to fix this.

@ewirch: as a workaround, you can replace your existing `main` method implementation with the following:

```java
//import io.micronaut.context.ApplicationContext;
//import io.micronaut.context.env.Environment;

public static void main(String[] args) throws Exception {
    Class<?> clazz = MyCommand.class;
    try (ApplicationContext context = ApplicationContext.build(clazz, Environment.CLI).start()) {
        class WorkaroundFactory implements CommandLine.IFactory {
            @Override
            public <K> K create(Class<K> cls) throws Exception {
                Optional<K> bean = context.findOrInstantiateBean(cls);
                return bean.isPresent() ? bean.get() : CommandLine.defaultFactory().create(cls);
            }
        }
        new CommandLine(clazz, new WorkaroundFactory()).execute(args);
    }
}
```

**Comment by jzinedine** [comment]
Interestingly this happens when you generate a fresh Micronaut cli app from the generator website.
<img width="1405" alt="Screenshot 2023-06-21 at 12 21 56 AM" src="https://github.com/micronaut-projects/micronaut-picocli/assets/503810/7326280e-4005-444c-90c9-ab13d76e56ba">
