### ISSUE TITLE
How to start properly a micronaut webserver from picocli command?

### ISSUE THREAD

**Issue by tchiotludo** [micronaut-projects/micronaut-picocli#9]
I've a [micronaut cli application](https://docs.micronaut.io/latest/guide/index.html#cli).

Some command are long running process that I want to monitor with [micronaut endpoints](https://docs.micronaut.io/latest/guide/index.html#management) 

Since when you are on a cli app, micronaut detect and don't launch the webserver. 

In this long running command, I've added this to start the webserver :  

```java
        applicationContext
            .findBean(EmbeddedServer.class)
            .ifPresent(server -> {
                // start server
                long start = System.currentTimeMillis();
                server.start();

                log.info(
                    "Startup completed in {} ms. Server Running: {}",
                    System.currentTimeMillis() - start,
                    server.getURL()
                );

                // force exit
                if (server.isForceExit()) {
                    System.exit(0);
                }
            });
```

Most of the code come from [Micronaut.java](https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/src/main/java/io/micronaut/runtime/Micronaut.java#L62).

The full command source code: 

```java
package test;
 
import io.micronaut.configuration.picocli.PicocliRunner;
import io.micronaut.context.ApplicationContext;
import io.micronaut.runtime.server.EmbeddedServer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import picocli.CommandLine;
 
import javax.inject.Inject;
import java.util.concurrent.Callable;
 
@CommandLine.Command(
    name = "test",
    mixinStandardHelpOptions = true,
    subcommands = {
        TestApp.TestServer.class,
    }
)
public class TestApp implements Callable<Object> {
    public static void main(String[] args) throws Exception {
        PicocliRunner.call(TestApp.class, args);
    }
 
    @Override
    public Object call() throws Exception {
        return PicocliRunner.call(TestApp.class, "--help");
    }
 
    @CommandLine.Command(
        name = "server",
        description = "Start a webserver"
    )
    public static class TestServer implements Runnable {
        @Inject
        ApplicationContext applicationContext;
 
        Logger log = LoggerFactory.getLogger(TestServer.class);
 
        @Override
        public void run() {
            applicationContext
                .findBean(EmbeddedServer.class)
                .ifPresent(server -> {
                    // start server
                    long start = System.currentTimeMillis();
                    server.start();
 
                    log.info(
                        "Startup completed in {} ms. Server Running: {}",
                        System.currentTimeMillis() - start,
                        server.getURL()
                    );
 
                    // force exit
                    if (server.isForceExit()) {
                        System.exit(0);
                    }
                });
        }
    }
}
```

The webserver is starting well. I've added 2 endpoints, logger and health.
Logger endpoint works well, but the health endpoint (like most every endpoint) failed with with this stacktrace : 
[Full Stacktrace](https://pastebin.com/mRzWZ0xi)
```
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1f5e667f[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@1615aa7e[Wrapped task = io.micronaut.http.context.ServerRequestContext$$Lambda$653/0x00000008406af040@5f7931cf]] rejected from java.util.concurrent.ThreadPoolExecutor@33dd1064[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
...
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1f5e667f[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@1615aa7e[Wrapped task = io.micronaut.http.context.ServerRequestContext$$Lambda$653/0x00000008406af040@5f7931cf]] rejected from java.util.concurrent.ThreadPoolExecutor@33dd1064[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
....
	at io.micronaut.scheduling.instrument.InstrumentedExecutorService.submit(InstrumentedExecutorService.java:89)
	at io.micronaut.core.async.publisher.AsyncSingleResultPublisher$ExecutorServiceSubscription.request(AsyncSingleResultPublisher.java:98)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onSubscribe(FlowableFlatMap.java:656)
	at io.micronaut.core.async.publisher.AsyncSingleResultPublisher.subscribe(AsyncSingleResultPublisher.java:59)
...
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	... 38 more
Exception in thread "nioEventLoopGroup-1-4" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1f5e667f[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@1615aa7e[Wrapped task = io.micronaut.http.context.ServerRequestContext$$Lambda$653/0x00000008406af040@5f7931cf]] rejected from java.util.concurrent.ThreadPoolExecutor@33dd1064[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
...
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	at io.micronaut.core.async.publisher.Publishers.lambda$map$2(Publishers.java:133)
...
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1f5e667f[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@1615aa7e[Wrapped task = io.micronaut.http.context.ServerRequestContext$$Lambda$653/0x00000008406af040@5f7931cf]] rejected from java.util.concurrent.ThreadPoolExecutor@33dd1064[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	... 38 more
2019-10-11 17:18:50,689 WARN  nioEventLoopGroup-1-4    i.n.u.c.AbstractEventExecutor        A task raised an exception. Task: io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker@7ebe5c10
java.lang.NullPointerException: Actually not, but can't throw other exceptions due to RS
	at io.reactivex.Flowable.subscribe(Flowable.java:14814)
...
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1f5e667f[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@1615aa7e[Wrapped task = io.micronaut.http.context.ServerRequestContext$$Lambda$653/0x00000008406af040@5f7931cf]] rejected from java.util.concurrent.ThreadPoolExecutor@33dd1064[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at io.micronaut.scheduling.instrument.InstrumentedExecutorService.submit(InstrumentedExecutorService.java:89)
	at io.micronaut.core.async.publisher.AsyncSingleResultPublisher$ExecutorServiceSubscription.request(AsyncSingleResultPublisher.java:98)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onSubscribe(FlowableFlatMap.java:656)
	at io.micronaut.core.async.publisher.AsyncSingleResultPublisher.subscribe(AsyncSingleResultPublisher.java:59)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.slowPath(FlowableFromIterable.java:236)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:124)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onSubscribe(FlowableFlatMap.java:117)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	... 38 common frames omitted
```

**Comment by graemerocher** [comment]
I believe this is because the netty server doesn't block the thread so it may already be in the process of shutting down when you send requests to it?

See the logic in the `Micronaut` class that uses a CountDownLatch to block and prevent shutdown

**Comment by tchiotludo** [comment]
Thanks for the response.

I have a look at `Micronaut` class and I'll try to copy paste the whole logic. 

Enable DEBUG log give me that : 
```
2019-10-14 11:18:11,023 INFO  main                     c.l.d.d.k.cli.TestApp$TestServer     Startup completed in 103ms. Server Running: http://127.0.0.1:27167
2019-10-14 11:18:11,025 DEBUG main                     i.m.context.DefaultBeanContext       Stopping BeanContext
2019-10-14 11:18:11,040 DEBUG main                     io.micronaut.context.lifecycle       Destroying bean [io.micronaut.http.server.netty.NettyHttpServer@7fb48179] with identifier [io.micronaut.http.server.netty.NettyHttpServer]
2019-10-14 11:18:11,040 DEBUG main                     io.micronaut.context.lifecycle       Destroying bean [io.micronaut.scheduling.executor.DefaultExecutorSelector@73d60e76] with identifier [io.micronaut.scheduling.executor.DefaultExecutorSelector]
...
2019-10-14 11:18:11,043 DEBUG main                     io.micronaut.context.lifecycle       Destroying bean [io.micronaut.scheduling.executor.UserExecutorConfiguration@5c723f2d] with identifier [@Named('io') io.micronaut.scheduling.executor.ExecutorConfiguration]
...
```
The BeanContext seems to stop automatically right after the server startup. 
And stop all the executor service right after.

Here is the caller stacktrace on `io.micronaut.context.DefaultBeanContext.stop()`
```
	at io.micronaut.context.DefaultBeanContext.stop(DefaultBeanContext.java:233)
	at io.micronaut.context.DefaultApplicationContext.stop(DefaultApplicationContext.java:192)
	at io.micronaut.context.DefaultApplicationContext.stop(DefaultApplicationContext.java:53)
	at io.micronaut.context.LifeCycle.close(LifeCycle.java:61)
	at io.micronaut.configuration.picocli.PicocliRunner.call(PicocliRunner.java:68)
	at test.TestApp.main(TestApp.java:26)
``` 

I just can figured where the stop is coming for now.

**Comment by graemerocher** [comment]
Seems to be https://github.com/micronaut-projects/micronaut-picocli/blob/master/picocli/src/main/java/io/micronaut/configuration/picocli/PicocliRunner.java#L66

Which stops the server after `call` so all logic has to complete in the scope of that `call` method

**Comment by tchiotludo** [comment]
Ok you got it !! 
My application is multi threaded application and the Command is not waiting for the thread to end.
So the `call` is ended silently (normal behavior) and the my thread keep the program running silently with an application context already closed.
  
Thanks to point me to the good direction :+1:

**Comment by swaechter** [comment]
@tchiotludo Were you able to resolve that issue and can you share a working, minimal example? We want to use Picocli and implement several subcommands, e.g. to create the configuration, migrate it etc. and the following example always exits:

```java
@Command(description = "Launch the web application")
public class Application implements Callable<Integer> {

    @Parameters(index = "0", description = "Path to the settings file")
    private File settingsFile;

    @Override
    public Integer call() throws Exception {
        // Check if the settings file exist
        if (!settingsFile.isFile()) {
            System.err.println("The file path " + settingsFile.getAbsolutePath() + " is not a file");
            System.exit(1);
        }

        // Set the system property
        System.setProperty("micronaut.config.files", settingsFile.getAbsolutePath());

        // Launch the application
        Micronaut.build(new String[]{}).mainClass(Application.class).banner(false).start();
        return 0; // TODO: Handle exit code...
    }

    public static void main(String[] arguments) {
        int exitCode = new CommandLine(new Application()).execute(arguments);
        System.exit(exitCode);
    }
}
```

**Comment by tchiotludo** [comment]
@swaechter you can find my implementation here: 
- [App.java](https://github.com/kestra-io/kestra/blob/develop/cli/src/main/java/io/kestra/cli/App.java)
- [AbstractCommand.java](https://github.com/kestra-io/kestra/blob/develop/cli/src/main/java/io/kestra/cli/AbstractCommand.java) that handle a base class that will start the embedded server 
- [a command that used the abstract class](https://github.com/kestra-io/kestra/blob/develop/cli/src/main/java/io/kestra/cli/commands/servers/WebServerCommand.java), see the trick with `Await.until(() -> !this.applicationContext.isRunning());` that will wait till the end of applicationContext to keep it running 

Hope it help

**Comment by swaechter** [comment]
Hey @tchiotludo. Thanks a lot for your fast reply and the code samples. The following code works (I don't need the DI context):

```java
ApplicationContext applicationContext = Micronaut.build(new String[]{}).mainClass(StartApplicationCommand.class).banner(false).start();
Await.until(() -> !applicationContext.isRunning());
System.out.println("Exited ");
```

But one question: You are using `Callable<Integer>`to transport the exit code. But in https://github.com/kestra-io/kestra/blob/develop/cli/src/main/java/io/kestra/cli/commands/servers/WebServerCommand.java#L41 you are returning `0`. Do you have a shutdown handler that keeps the original Micronaut exit code or is it overwritten (Background: You are running your application in a Container/Linux systemd/Windows service. The application crashes and returns 0 with means "Proper shutdown" - some systems won't restart the service)

**Comment by tchiotludo** [comment]
The return 0 meaning it's ok (normal shutdown via signal handler for example in containers). 
For any others unhandled exceptions, it's will be forward and it will crash the application with a signal <> 0 as i see, since in Kubernetes I received `CrashLoopBackOff` for fatal error.
